apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ep-133-cms.fullname" . }}-secret
  labels:
    {{- include "ep-133-cms.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
